project_id = "wsqshdjljgejrrbthjha"

[functions.social-auth]
verify_jwt = true

[functions.facebook-auth]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.generate-personas]
verify_jwt = true

[functions.secure-social-connections]
verify_jwt = true

[functions.secure-admin-moderation]
verify_jwt = true

[functions.secure-social-auth]
verify_jwt = true