// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsqshdjljgejrrbthjha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcXNoZGpsamdlanJyYnRoamhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTUxNTgsImV4cCI6MjA2NTE3MTE1OH0.ET0XWmZF1AMb6qvf2Hh168dQtQGGTPFzO_JFyjSFyS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);